export { default as Home } from './home.js'
export { default as LoginRegister } from './loginRegister.js'
// export { default as Register } from './register.js'
export { default as Activities } from './activities.js'
export { default as Routines } from './routines.js'
export { default as Header } from './header.js'